### PR TITLE
More flexible soft change checks (issue #34)

### PR DESCRIPTION
**Pull request by emirpprime**
- case insensitivity in filenames
- accept .md extension as well as .txt

### CODE REVIEW

**Comment by emirpprime** [comment]
Ah - silly error. How do I test against a file that doesn't exist (readme.md)? Or will the test need to install another plugin that does use readme.md and then test against that?

**Comment by schlessera** [comment]
@emirpprime Yes, you need to use a plugin that actually exhibits the problematic behavior.

You can use the one that triggered the [initial issue](https://github.com/wp-cli/wp-cli/issues/4681), it was [document-gallery](https://wordpress.org/plugins/document-gallery/).

**Comment by schlessera** [comment]
@emirpprime You should also merge latest master, which fixes the memory issue with PHP 5.3 tests.

**Comment by schlessera** [comment]
😳  GitHub, why is this closed now???

I'm sorry, @emirpprime, I was just pushing the update to get the memory fix for PHP 5.3.

Something with the pull-request must have been messed up internally, because I pushed the change into your fork's `master`, which immediately closed the PR here.

Also I cannot seem to reopen it:
image 2018-04-19 at 5 29 04 pm

If you still care to add this functionality, please open a new PR with your changes. I'm very sorry for wasting your time here.

**Comment by schlessera** [comment]
For reference, here's a diff of the code:
image 2018-04-19 at 5 34 33 pm

**Comment by schlessera** [comment]
Continued in #43

**Pull request closed without merging**
