### PR TITLE
Change naming of checksum commands

### LINKED ISSUE #14: Rename `wp checksum core` back to `wp core verify-checksums`
The original rename is a decision I regret. Most WP-CLI commands are verbs, so we should make this a verb too.

### PR DESCRIPTION
**Pull request by schlessera**
`wp checksum core` => `wp core verify-checksums`
`wp checksum plugin` => `wp plugin verify-checksums`

Fixes #14

### CODE REVIEW

**Comment by schlessera** [comment]
Tests will only pass once https://github.com/wp-cli/wp-cli/pull/4639 has been merged.

**Comment by gitlost** [comment]
Sorry restarted the build without realizing the PR was incomplete.

**Comment by gitlost** [comment]
@schlessera I'm totally confused by this. Does something need to happen now to `wp-cli/wp-cli`  to get this to work?

**Comment by gitlost** [comment]
@schlessera perhaps we should revert this and https://github.com/wp-cli/wp-cli/pull/4639 and leave the name change to after the release??

**Comment by schlessera** [comment]
No, I'm fixing this now. The `wp-cli/wp-cli` Composer lock file contained references to old versions still. After proper releases and updating the lock file, it should (mostly) work. It does work on local here.

**Comment by gitlost** [comment]
Ta.

**Pull request merged**
